-- Enable per-user bot trading profiles and authenticated TradingView webhooks.
alter table public.profiles
  add column if not exists trading_profile text not null default 'balanced',
  add column if not exists tradingview_webhook_token text;

update public.profiles
set trading_profile = 'balanced'
where trading_profile is null
   or trading_profile not in ('aggressive', 'balanced', 'conservative');

alter table public.profiles
  drop constraint if exists profiles_trading_profile_check;

alter table public.profiles
  add constraint profiles_trading_profile_check
  check (trading_profile in ('aggressive', 'balanced', 'conservative'));

create unique index if not exists idx_profiles_tradingview_webhook_token
  on public.profiles (tradingview_webhook_token)
  where tradingview_webhook_token is not null;

create table if not exists public.tradingview_signals (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  symbol text not null,
  direction text not null check (direction in ('BUY', 'SELL')),
  payload jsonb not null default '{}'::jsonb,
  status text not null default 'pending',
  received_at timestamptz not null default now(),
  processed_at timestamptz
);

create index if not exists idx_tradingview_signals_user_received
  on public.tradingview_signals (user_id, received_at desc);

create index if not exists idx_tradingview_signals_pending
  on public.tradingview_signals (status, received_at)
  where status = 'pending';

alter table public.tradingview_signals enable row level security;

drop policy if exists "Users can view own TradingView signals" on public.tradingview_signals;
create policy "Users can view own TradingView signals"
  on public.tradingview_signals
  for select
  using (auth.uid() = user_id);
